package com.soft.po;

import java.util.Date;

public class TransAnalysis {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_analysis.analysis_id
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    private Integer analysisId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_analysis.method
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_analysis.symbol
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    private String symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_analysis.price
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_analysis.depth
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    private String depth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_analysis.percent
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    private String percent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_analysis.create_time
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_analysis.analysis_id
     *
     * @return the value of trans_analysis.analysis_id
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    public Integer getAnalysisId() {
        return analysisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_analysis.analysis_id
     *
     * @param analysisId the value for trans_analysis.analysis_id
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    public void setAnalysisId(Integer analysisId) {
        this.analysisId = analysisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_analysis.method
     *
     * @return the value of trans_analysis.method
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_analysis.method
     *
     * @param method the value for trans_analysis.method
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_analysis.symbol
     *
     * @return the value of trans_analysis.symbol
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_analysis.symbol
     *
     * @param symbol the value for trans_analysis.symbol
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_analysis.price
     *
     * @return the value of trans_analysis.price
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_analysis.price
     *
     * @param price the value for trans_analysis.price
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_analysis.depth
     *
     * @return the value of trans_analysis.depth
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    public String getDepth() {
        return depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_analysis.depth
     *
     * @param depth the value for trans_analysis.depth
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    public void setDepth(String depth) {
        this.depth = depth == null ? null : depth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_analysis.percent
     *
     * @return the value of trans_analysis.percent
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    public String getPercent() {
        return percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_analysis.percent
     *
     * @param percent the value for trans_analysis.percent
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    public void setPercent(String percent) {
        this.percent = percent == null ? null : percent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_analysis.create_time
     *
     * @return the value of trans_analysis.create_time
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_analysis.create_time
     *
     * @param createTime the value for trans_analysis.create_time
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}