package com.soft.po;

import java.util.Date;

public class TransPrepareOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_prepare_order.prepare_order_id
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    private Integer prepareOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_prepare_order.event_id
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    private Integer eventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_prepare_order.huo_order_id
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    private String huoOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_prepare_order.symbol
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    private String symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_prepare_order.type
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_prepare_order.amount
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    private String amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_prepare_order.price
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_prepare_order.state
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_prepare_order.create_time
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_prepare_order.prepare_order_id
     *
     * @return the value of trans_prepare_order.prepare_order_id
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public Integer getPrepareOrderId() {
        return prepareOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_prepare_order.prepare_order_id
     *
     * @param prepareOrderId the value for trans_prepare_order.prepare_order_id
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public void setPrepareOrderId(Integer prepareOrderId) {
        this.prepareOrderId = prepareOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_prepare_order.event_id
     *
     * @return the value of trans_prepare_order.event_id
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public Integer getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_prepare_order.event_id
     *
     * @param eventId the value for trans_prepare_order.event_id
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_prepare_order.huo_order_id
     *
     * @return the value of trans_prepare_order.huo_order_id
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public String getHuoOrderId() {
        return huoOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_prepare_order.huo_order_id
     *
     * @param huoOrderId the value for trans_prepare_order.huo_order_id
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public void setHuoOrderId(String huoOrderId) {
        this.huoOrderId = huoOrderId == null ? null : huoOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_prepare_order.symbol
     *
     * @return the value of trans_prepare_order.symbol
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_prepare_order.symbol
     *
     * @param symbol the value for trans_prepare_order.symbol
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_prepare_order.type
     *
     * @return the value of trans_prepare_order.type
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_prepare_order.type
     *
     * @param type the value for trans_prepare_order.type
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_prepare_order.amount
     *
     * @return the value of trans_prepare_order.amount
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_prepare_order.amount
     *
     * @param amount the value for trans_prepare_order.amount
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_prepare_order.price
     *
     * @return the value of trans_prepare_order.price
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_prepare_order.price
     *
     * @param price the value for trans_prepare_order.price
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_prepare_order.state
     *
     * @return the value of trans_prepare_order.state
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_prepare_order.state
     *
     * @param state the value for trans_prepare_order.state
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_prepare_order.create_time
     *
     * @return the value of trans_prepare_order.create_time
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_prepare_order.create_time
     *
     * @param createTime the value for trans_prepare_order.create_time
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}