package com.soft.po;

public class TransAnalysisTradeStart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_analysis_trade_start.start_id
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    private Integer startId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_analysis_trade_start.up
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    private String up;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_analysis_trade_start.down
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    private String down;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_analysis_trade_start.up_order
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    private String upOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_analysis_trade_start.down_order
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    private String downOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_analysis_trade_start.upflag
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    private String upflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_analysis_trade_start.downflag
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    private String downflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_analysis_trade_start.buy_condition
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    private String buyCondition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_analysis_trade_start.sell_condition
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    private String sellCondition;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_analysis_trade_start.start_id
     *
     * @return the value of trans_analysis_trade_start.start_id
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public Integer getStartId() {
        return startId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_analysis_trade_start.start_id
     *
     * @param startId the value for trans_analysis_trade_start.start_id
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public void setStartId(Integer startId) {
        this.startId = startId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_analysis_trade_start.up
     *
     * @return the value of trans_analysis_trade_start.up
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public String getUp() {
        return up;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_analysis_trade_start.up
     *
     * @param up the value for trans_analysis_trade_start.up
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public void setUp(String up) {
        this.up = up == null ? null : up.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_analysis_trade_start.down
     *
     * @return the value of trans_analysis_trade_start.down
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public String getDown() {
        return down;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_analysis_trade_start.down
     *
     * @param down the value for trans_analysis_trade_start.down
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public void setDown(String down) {
        this.down = down == null ? null : down.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_analysis_trade_start.up_order
     *
     * @return the value of trans_analysis_trade_start.up_order
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public String getUpOrder() {
        return upOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_analysis_trade_start.up_order
     *
     * @param upOrder the value for trans_analysis_trade_start.up_order
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public void setUpOrder(String upOrder) {
        this.upOrder = upOrder == null ? null : upOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_analysis_trade_start.down_order
     *
     * @return the value of trans_analysis_trade_start.down_order
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public String getDownOrder() {
        return downOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_analysis_trade_start.down_order
     *
     * @param downOrder the value for trans_analysis_trade_start.down_order
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public void setDownOrder(String downOrder) {
        this.downOrder = downOrder == null ? null : downOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_analysis_trade_start.upflag
     *
     * @return the value of trans_analysis_trade_start.upflag
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public String getUpflag() {
        return upflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_analysis_trade_start.upflag
     *
     * @param upflag the value for trans_analysis_trade_start.upflag
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public void setUpflag(String upflag) {
        this.upflag = upflag == null ? null : upflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_analysis_trade_start.downflag
     *
     * @return the value of trans_analysis_trade_start.downflag
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public String getDownflag() {
        return downflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_analysis_trade_start.downflag
     *
     * @param downflag the value for trans_analysis_trade_start.downflag
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public void setDownflag(String downflag) {
        this.downflag = downflag == null ? null : downflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_analysis_trade_start.buy_condition
     *
     * @return the value of trans_analysis_trade_start.buy_condition
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public String getBuyCondition() {
        return buyCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_analysis_trade_start.buy_condition
     *
     * @param buyCondition the value for trans_analysis_trade_start.buy_condition
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public void setBuyCondition(String buyCondition) {
        this.buyCondition = buyCondition == null ? null : buyCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_analysis_trade_start.sell_condition
     *
     * @return the value of trans_analysis_trade_start.sell_condition
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public String getSellCondition() {
        return sellCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_analysis_trade_start.sell_condition
     *
     * @param sellCondition the value for trans_analysis_trade_start.sell_condition
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public void setSellCondition(String sellCondition) {
        this.sellCondition = sellCondition == null ? null : sellCondition.trim();
    }
}