package com.soft.po;

import java.util.Date;

public class TransOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_order.order_id
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_order.prepare_order_id
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    private Integer prepareOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_order.event_id
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    private Integer eventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_order.huo_order_id
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    private String huoOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_order.huo_symbol
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    private String huoSymbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_order.huo_type
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    private String huoType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_order.huo_amount
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    private String huoAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_order.huo_price
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    private String huoPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_order.huo_state
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    private String huoState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_order.huo_created_time
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    private Date huoCreatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_order.huo_canceled_time
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    private Date huoCanceledTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_order.huo_finished_time
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    private Date huoFinishedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_order.huo_filled_cash_amount
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    private String huoFilledCashAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_order.huo_filled_amount
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    private String huoFilledAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_order.huo_filled_fees
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    private String huoFilledFees;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_order.create_time
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_order.order_id
     *
     * @return the value of trans_order.order_id
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_order.order_id
     *
     * @param orderId the value for trans_order.order_id
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_order.prepare_order_id
     *
     * @return the value of trans_order.prepare_order_id
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public Integer getPrepareOrderId() {
        return prepareOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_order.prepare_order_id
     *
     * @param prepareOrderId the value for trans_order.prepare_order_id
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public void setPrepareOrderId(Integer prepareOrderId) {
        this.prepareOrderId = prepareOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_order.event_id
     *
     * @return the value of trans_order.event_id
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public Integer getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_order.event_id
     *
     * @param eventId the value for trans_order.event_id
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_order.huo_order_id
     *
     * @return the value of trans_order.huo_order_id
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public String getHuoOrderId() {
        return huoOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_order.huo_order_id
     *
     * @param huoOrderId the value for trans_order.huo_order_id
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public void setHuoOrderId(String huoOrderId) {
        this.huoOrderId = huoOrderId == null ? null : huoOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_order.huo_symbol
     *
     * @return the value of trans_order.huo_symbol
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public String getHuoSymbol() {
        return huoSymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_order.huo_symbol
     *
     * @param huoSymbol the value for trans_order.huo_symbol
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public void setHuoSymbol(String huoSymbol) {
        this.huoSymbol = huoSymbol == null ? null : huoSymbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_order.huo_type
     *
     * @return the value of trans_order.huo_type
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public String getHuoType() {
        return huoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_order.huo_type
     *
     * @param huoType the value for trans_order.huo_type
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public void setHuoType(String huoType) {
        this.huoType = huoType == null ? null : huoType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_order.huo_amount
     *
     * @return the value of trans_order.huo_amount
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public String getHuoAmount() {
        return huoAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_order.huo_amount
     *
     * @param huoAmount the value for trans_order.huo_amount
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public void setHuoAmount(String huoAmount) {
        this.huoAmount = huoAmount == null ? null : huoAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_order.huo_price
     *
     * @return the value of trans_order.huo_price
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public String getHuoPrice() {
        return huoPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_order.huo_price
     *
     * @param huoPrice the value for trans_order.huo_price
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public void setHuoPrice(String huoPrice) {
        this.huoPrice = huoPrice == null ? null : huoPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_order.huo_state
     *
     * @return the value of trans_order.huo_state
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public String getHuoState() {
        return huoState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_order.huo_state
     *
     * @param huoState the value for trans_order.huo_state
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public void setHuoState(String huoState) {
        this.huoState = huoState == null ? null : huoState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_order.huo_created_time
     *
     * @return the value of trans_order.huo_created_time
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public Date getHuoCreatedTime() {
        return huoCreatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_order.huo_created_time
     *
     * @param huoCreatedTime the value for trans_order.huo_created_time
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public void setHuoCreatedTime(Date huoCreatedTime) {
        this.huoCreatedTime = huoCreatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_order.huo_canceled_time
     *
     * @return the value of trans_order.huo_canceled_time
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public Date getHuoCanceledTime() {
        return huoCanceledTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_order.huo_canceled_time
     *
     * @param huoCanceledTime the value for trans_order.huo_canceled_time
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public void setHuoCanceledTime(Date huoCanceledTime) {
        this.huoCanceledTime = huoCanceledTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_order.huo_finished_time
     *
     * @return the value of trans_order.huo_finished_time
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public Date getHuoFinishedTime() {
        return huoFinishedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_order.huo_finished_time
     *
     * @param huoFinishedTime the value for trans_order.huo_finished_time
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public void setHuoFinishedTime(Date huoFinishedTime) {
        this.huoFinishedTime = huoFinishedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_order.huo_filled_cash_amount
     *
     * @return the value of trans_order.huo_filled_cash_amount
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public String getHuoFilledCashAmount() {
        return huoFilledCashAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_order.huo_filled_cash_amount
     *
     * @param huoFilledCashAmount the value for trans_order.huo_filled_cash_amount
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public void setHuoFilledCashAmount(String huoFilledCashAmount) {
        this.huoFilledCashAmount = huoFilledCashAmount == null ? null : huoFilledCashAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_order.huo_filled_amount
     *
     * @return the value of trans_order.huo_filled_amount
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public String getHuoFilledAmount() {
        return huoFilledAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_order.huo_filled_amount
     *
     * @param huoFilledAmount the value for trans_order.huo_filled_amount
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public void setHuoFilledAmount(String huoFilledAmount) {
        this.huoFilledAmount = huoFilledAmount == null ? null : huoFilledAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_order.huo_filled_fees
     *
     * @return the value of trans_order.huo_filled_fees
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public String getHuoFilledFees() {
        return huoFilledFees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_order.huo_filled_fees
     *
     * @param huoFilledFees the value for trans_order.huo_filled_fees
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public void setHuoFilledFees(String huoFilledFees) {
        this.huoFilledFees = huoFilledFees == null ? null : huoFilledFees.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_order.create_time
     *
     * @return the value of trans_order.create_time
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_order.create_time
     *
     * @param createTime the value for trans_order.create_time
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}