package com.soft.po;

public class TransAnalysisTradeResult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_analysis_trade_result.result_id
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    private Integer resultId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_analysis_trade_result.money
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    private String money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_analysis_trade_result.count_buy_all
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    private String countBuyAll;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_analysis_trade_result.count_sell_all
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    private String countSellAll;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_analysis_trade_result.high_money
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    private String highMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_analysis_trade_result.low_money
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    private String lowMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_analysis_trade_result.result_id
     *
     * @return the value of trans_analysis_trade_result.result_id
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public Integer getResultId() {
        return resultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_analysis_trade_result.result_id
     *
     * @param resultId the value for trans_analysis_trade_result.result_id
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public void setResultId(Integer resultId) {
        this.resultId = resultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_analysis_trade_result.money
     *
     * @return the value of trans_analysis_trade_result.money
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_analysis_trade_result.money
     *
     * @param money the value for trans_analysis_trade_result.money
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public void setMoney(String money) {
        this.money = money == null ? null : money.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_analysis_trade_result.count_buy_all
     *
     * @return the value of trans_analysis_trade_result.count_buy_all
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public String getCountBuyAll() {
        return countBuyAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_analysis_trade_result.count_buy_all
     *
     * @param countBuyAll the value for trans_analysis_trade_result.count_buy_all
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public void setCountBuyAll(String countBuyAll) {
        this.countBuyAll = countBuyAll == null ? null : countBuyAll.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_analysis_trade_result.count_sell_all
     *
     * @return the value of trans_analysis_trade_result.count_sell_all
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public String getCountSellAll() {
        return countSellAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_analysis_trade_result.count_sell_all
     *
     * @param countSellAll the value for trans_analysis_trade_result.count_sell_all
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public void setCountSellAll(String countSellAll) {
        this.countSellAll = countSellAll == null ? null : countSellAll.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_analysis_trade_result.high_money
     *
     * @return the value of trans_analysis_trade_result.high_money
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public String getHighMoney() {
        return highMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_analysis_trade_result.high_money
     *
     * @param highMoney the value for trans_analysis_trade_result.high_money
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public void setHighMoney(String highMoney) {
        this.highMoney = highMoney == null ? null : highMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_analysis_trade_result.low_money
     *
     * @return the value of trans_analysis_trade_result.low_money
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public String getLowMoney() {
        return lowMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_analysis_trade_result.low_money
     *
     * @param lowMoney the value for trans_analysis_trade_result.low_money
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    public void setLowMoney(String lowMoney) {
        this.lowMoney = lowMoney == null ? null : lowMoney.trim();
    }
}