package com.soft.po;

public class TransSettle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_settle.settle_id
     *
     * @mbg.generated Wed Sep 11 17:23:43 CST 2019
     */
    private Integer settleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_settle.event_id
     *
     * @mbg.generated Wed Sep 11 17:23:43 CST 2019
     */
    private Integer eventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_settle.settle_state
     *
     * @mbg.generated Wed Sep 11 17:23:43 CST 2019
     */
    private String settleState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_settle.settle_total
     *
     * @mbg.generated Wed Sep 11 17:23:43 CST 2019
     */
    private String settleTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_settle.settle_earn
     *
     * @mbg.generated Wed Sep 11 17:23:43 CST 2019
     */
    private String settleEarn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_settle.settle_percent
     *
     * @mbg.generated Wed Sep 11 17:23:43 CST 2019
     */
    private String settlePercent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_settle.settle_id
     *
     * @return the value of trans_settle.settle_id
     *
     * @mbg.generated Wed Sep 11 17:23:43 CST 2019
     */
    public Integer getSettleId() {
        return settleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_settle.settle_id
     *
     * @param settleId the value for trans_settle.settle_id
     *
     * @mbg.generated Wed Sep 11 17:23:43 CST 2019
     */
    public void setSettleId(Integer settleId) {
        this.settleId = settleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_settle.event_id
     *
     * @return the value of trans_settle.event_id
     *
     * @mbg.generated Wed Sep 11 17:23:43 CST 2019
     */
    public Integer getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_settle.event_id
     *
     * @param eventId the value for trans_settle.event_id
     *
     * @mbg.generated Wed Sep 11 17:23:43 CST 2019
     */
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_settle.settle_state
     *
     * @return the value of trans_settle.settle_state
     *
     * @mbg.generated Wed Sep 11 17:23:43 CST 2019
     */
    public String getSettleState() {
        return settleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_settle.settle_state
     *
     * @param settleState the value for trans_settle.settle_state
     *
     * @mbg.generated Wed Sep 11 17:23:43 CST 2019
     */
    public void setSettleState(String settleState) {
        this.settleState = settleState == null ? null : settleState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_settle.settle_total
     *
     * @return the value of trans_settle.settle_total
     *
     * @mbg.generated Wed Sep 11 17:23:43 CST 2019
     */
    public String getSettleTotal() {
        return settleTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_settle.settle_total
     *
     * @param settleTotal the value for trans_settle.settle_total
     *
     * @mbg.generated Wed Sep 11 17:23:43 CST 2019
     */
    public void setSettleTotal(String settleTotal) {
        this.settleTotal = settleTotal == null ? null : settleTotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_settle.settle_earn
     *
     * @return the value of trans_settle.settle_earn
     *
     * @mbg.generated Wed Sep 11 17:23:43 CST 2019
     */
    public String getSettleEarn() {
        return settleEarn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_settle.settle_earn
     *
     * @param settleEarn the value for trans_settle.settle_earn
     *
     * @mbg.generated Wed Sep 11 17:23:43 CST 2019
     */
    public void setSettleEarn(String settleEarn) {
        this.settleEarn = settleEarn == null ? null : settleEarn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_settle.settle_percent
     *
     * @return the value of trans_settle.settle_percent
     *
     * @mbg.generated Wed Sep 11 17:23:43 CST 2019
     */
    public String getSettlePercent() {
        return settlePercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_settle.settle_percent
     *
     * @param settlePercent the value for trans_settle.settle_percent
     *
     * @mbg.generated Wed Sep 11 17:23:43 CST 2019
     */
    public void setSettlePercent(String settlePercent) {
        this.settlePercent = settlePercent == null ? null : settlePercent.trim();
    }
}