package com.soft.po;

public class TransEvent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_event.event_id
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    private Integer eventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_event.method
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_event.state
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_event.total
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    private String total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_event.earn
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    private String earn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trans_event.percent
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    private String percent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_event.event_id
     *
     * @return the value of trans_event.event_id
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public Integer getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_event.event_id
     *
     * @param eventId the value for trans_event.event_id
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_event.method
     *
     * @return the value of trans_event.method
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_event.method
     *
     * @param method the value for trans_event.method
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_event.state
     *
     * @return the value of trans_event.state
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_event.state
     *
     * @param state the value for trans_event.state
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_event.total
     *
     * @return the value of trans_event.total
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public String getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_event.total
     *
     * @param total the value for trans_event.total
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public void setTotal(String total) {
        this.total = total == null ? null : total.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_event.earn
     *
     * @return the value of trans_event.earn
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public String getEarn() {
        return earn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_event.earn
     *
     * @param earn the value for trans_event.earn
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public void setEarn(String earn) {
        this.earn = earn == null ? null : earn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trans_event.percent
     *
     * @return the value of trans_event.percent
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public String getPercent() {
        return percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trans_event.percent
     *
     * @param percent the value for trans_event.percent
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    public void setPercent(String percent) {
        this.percent = percent == null ? null : percent.trim();
    }
}