package com.soft.mapper;

import com.soft.po.TransPrepareOrder;

import java.util.List;

public interface TransPrepareOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_prepare_order
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    int deleteByPrimaryKey(Integer prepareOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_prepare_order
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    int insert(TransPrepareOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_prepare_order
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    int insertSelective(TransPrepareOrder record);

    TransPrepareOrder selectByPrimaryKey(Integer prepareOrderId);

    //查询全部
    List<TransPrepareOrder> selectAll(TransPrepareOrder transPrepareOrder);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_prepare_order
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    int updateByPrimaryKeySelective(TransPrepareOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_prepare_order
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    int updateByPrimaryKey(TransPrepareOrder record);
}