package com.soft.mapper;

import com.soft.po.TransEvent;

import java.util.List;

public interface TransEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_event
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    int deleteByPrimaryKey(Integer eventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_event
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    int insert(TransEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_event
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    int insertSelective(TransEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_event
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    TransEvent selectByPrimaryKey(Integer eventId);

    //查询全部
    List<TransEvent> selectAll(TransEvent transEvent);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_event
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    int updateByPrimaryKeySelective(TransEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_event
     *
     * @mbg.generated Sun Sep 08 12:59:05 CST 2019
     */
    int updateByPrimaryKey(TransEvent record);
}