package com.soft.mapper;

import com.soft.po.TransAnalysisTradeResult;

public interface TransAnalysisTradeResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_analysis_trade_result
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    int deleteByPrimaryKey(Integer resultId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_analysis_trade_result
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    int insert(TransAnalysisTradeResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_analysis_trade_result
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    int insertSelective(TransAnalysisTradeResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_analysis_trade_result
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    TransAnalysisTradeResult selectByPrimaryKey(Integer resultId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_analysis_trade_result
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    int updateByPrimaryKeySelective(TransAnalysisTradeResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_analysis_trade_result
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    int updateByPrimaryKey(TransAnalysisTradeResult record);
}