package com.soft.mapper;

import com.soft.po.TransSettle;

public interface TransSettleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_settle
     *
     * @mbg.generated Wed Sep 11 17:23:43 CST 2019
     */
    int deleteByPrimaryKey(Integer settleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_settle
     *
     * @mbg.generated Wed Sep 11 17:23:43 CST 2019
     */
    int insert(TransSettle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_settle
     *
     * @mbg.generated Wed Sep 11 17:23:43 CST 2019
     */
    int insertSelective(TransSettle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_settle
     *
     * @mbg.generated Wed Sep 11 17:23:43 CST 2019
     */
    TransSettle selectByPrimaryKey(Integer settleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_settle
     *
     * @mbg.generated Wed Sep 11 17:23:43 CST 2019
     */
    int updateByPrimaryKeySelective(TransSettle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_settle
     *
     * @mbg.generated Wed Sep 11 17:23:43 CST 2019
     */
    int updateByPrimaryKey(TransSettle record);
}