package com.soft.mapper;

import com.soft.po.TransOrder;

import java.util.List;

public interface TransOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_order
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_order
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    int insert(TransOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_order
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    int insertSelective(TransOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_order
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    TransOrder selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_order
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    int updateByPrimaryKeySelective(TransOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_order
     *
     * @mbg.generated Wed Sep 11 14:53:35 CST 2019
     */
    int updateByPrimaryKey(TransOrder record);


    //============================ private ==========================================

    /**
     * 查询全部符合条件的订单
     * @param transOrder
     * @return
     */
    List<TransOrder> selectAll(TransOrder transOrder);
}