package com.soft.mapper;

import com.soft.po.TransAnalysisTrade;

public interface TransAnalysisTradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_analysis_trade
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    int deleteByPrimaryKey(Integer tradeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_analysis_trade
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    int insert(TransAnalysisTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_analysis_trade
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    int insertSelective(TransAnalysisTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_analysis_trade
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    TransAnalysisTrade selectByPrimaryKey(Integer tradeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_analysis_trade
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    int updateByPrimaryKeySelective(TransAnalysisTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_analysis_trade
     *
     * @mbg.generated Sat Oct 12 16:33:37 CST 2019
     */
    int updateByPrimaryKey(TransAnalysisTrade record);
}