package com.soft.mapper;

import com.soft.po.TransAnalysis;

public interface TransAnalysisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_analysis
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    int deleteByPrimaryKey(Integer analysisId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_analysis
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    int insert(TransAnalysis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_analysis
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    int insertSelective(TransAnalysis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_analysis
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    TransAnalysis selectByPrimaryKey(Integer analysisId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_analysis
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    int updateByPrimaryKeySelective(TransAnalysis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_analysis
     *
     * @mbg.generated Tue Sep 17 16:05:50 CST 2019
     */
    int updateByPrimaryKey(TransAnalysis record);
}